### ISSUE TITLE
Jitter output has duplicate text

### ISSUE THREAD

**Issue by ghost** [mrpappas/squeaky-wheel#1]
For example, in the output log file, the Jitter line looks like this:

Jitter: 50 msec msec 

In the else block that writes this text, the msec needs to be removed sine the website also stores that text.

**Comment by mrpappas** [comment]
Good catch, thanks.

**Comment by mrpappas** [comment]
Duplicate text removed, closing this one.    
https://github.com/mrpappas/squeaky-wheel/commit/258e775dc10b2da9c4d444837f60ac9cd32e0d74
