### ISSUE TITLE
Add support for non-default Firefox locations

### ISSUE THREAD

**Issue by stumpylog** [mrpappas/squeaky-wheel#3]
At least on Windows, it appears selenium looks for the Firefox executable under `C:\Program Files\Mozilla Firefox\`.  This will fails on a 64 bit computer, where the executable is under `C:\Program Files (x86)\Mozilla Firefox\`.  

Adding support for a non-default location will fix this, and also allow other locations to be provided, such as ones that are outside of the normal installation directories or to use a portable Firefox.

I would propose adding a configuration file item to allow this to be specific.  If this is filled in, use that binary location as:
```
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
...
binary = FirefoxBinary('C:\Program Files (x86)\Mozilla Firefox\Firefox.exe')
...
driver = webdriver.Firefox(firefox_binary=binary)
```

with the appropriate information filled in from either the configuration or elsewhere.

**Comment by mrpappas** [comment]
Good deal, I agree.  Would you be up to it?  I am going to be doing some refactoring this evening based on [this comment](https://www.reddit.com/r/learnprogramming/comments/5iat63/i_was_pissed_at_comcasttime_warner_so_i_wrote/db6ue6e/) from the reddit thread.   
  
Edit:  also what do you think about adding a config option for different drivers (chrome driver, marionette)?

**Comment by stumpylog** [comment]
I may have to depend on some of that refactoring so that I can access an instance of the Config class inside init_driver.  If it won't step on your toes, mind if I refactor just the SpeedTest class?

I would disagree with making a new `DriverFactory.createFireFoxDriver` of that coment.  Why not create the driver in the `__init__` and keep one driver associated with one SpeedTest?  Not that we'd run into it here, but if a single driver from `DriverFactory.createFireFoxDriver` was used in two SpeedTest instances, wouldn't that cause issues?  I've never used one before, but it seems a little wonky.

Sure, I will look into using different drivers and allowing configuration of them

**Comment by mrpappas** [comment]
Accepted pull request to add add support for alternative drivers and firefox locations, going to close this now.  [Merge pull request from stumpylog/master](https://github.com/mrpappas/squeaky-wheel/commit/8c59b8fbefbf6fbaa11a3ac2d712bed3d1ae091f)
