### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by rahulkapoor90** [mrpappas/squeaky-wheel#5]
I am trying to use this script in windows but I keep getting this error. any idea?
```

  File "squeaky-wheel.py", line 74
    def __init__(self, config:Config):
                             ^
SyntaxError: invalid syntax

```

**Comment by stumpylog** [comment]
Are you using Python 2?  That syntax is the new type hinting in Python 3

**Comment by mrpappas** [comment]
Closing this, looks like OP was not using correct version of Python.
